//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fxhp_formLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        public string masv { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public Nullable<int> phone { get; set; }
        public string malop { get; set; }
    }
}
